    -- ============================================================================
    -- MODA Employee Bulk Import - 143 Employees from Employee_Directory_2025-12-01
    -- Generated from: Employee_Directory_2025-12-01 - for testing.xlsx
    -- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/syreuphexagezawjyjgt/sql/new
    -- ============================================================================

    -- Clear existing employees first (optional - uncomment if you want a fresh start)
    -- DELETE FROM employees WHERE true;

    INSERT INTO employees (first_name, last_name, job_title, department, shift, hire_date, permissions, access_status, is_active)
    VALUES
        ('Jon', 'Pope', 'Line Solutioneer', 'AVICAB', 'Shift-A', '2023-12-18', 'No Access', 'none', true),
        ('Ernest', 'Garcia', 'Line Solutioneer', 'AVICAB', 'Shift-A', '2023-01-09', 'No Access', 'none', true),
        ('David', 'Cornett', 'Line Solutioneer', 'AVICAB', 'Shift-A', '2022-02-21', 'No Access', 'none', true),
        ('Gregory', 'Pelkey', 'Line Solutioneer', 'AVICAB', 'Shift-A', '2021-04-19', 'No Access', 'none', true),
        ('Joseph', 'Hartley', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2025-06-09', 'No Access', 'none', true),
        ('Cody', 'Ullrich', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2025-03-24', 'No Access', 'none', true),
        ('Jesse', 'Boling', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2025-02-10', 'No Access', 'none', true),
        ('Daniel', 'Thornburg', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2024-08-05', 'No Access', 'none', true),
        ('Audrey', 'Del Bosque', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2024-07-29', 'No Access', 'none', true),
        ('Jonathan', 'Goad', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2024-05-20', 'No Access', 'none', true),
        ('Victor', 'Olvera', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2023-08-07', 'No Access', 'none', true),
        ('Jaime', 'Gordillo Vila', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2022-03-14', 'No Access', 'none', true),
        ('Joshua', 'Dialogue', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2021-11-29', 'No Access', 'none', true),
        ('Tyler', 'Howard', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2021-09-07', 'No Access', 'none', true),
        ('Donald', 'Power', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2021-04-26', 'No Access', 'none', true),
        ('George', 'White', 'Line Solutioneer', 'AVICEI', 'Shift-A', '2020-02-17', 'No Access', 'none', true),
        ('Valeriy', 'Kastyuk', 'Line Solutioneer', 'AVIDOR', 'Shift-A', '2025-06-02', 'No Access', 'none', true),
        ('Melissa', 'Reisinger', 'Line Solutioneer', 'AVIDOR', 'Shift-A', '2023-10-02', 'No Access', 'none', true),
        ('Jhon', 'Rubio', 'Line Solutioneer', 'AVIDOR', 'Shift-A', '2023-09-11', 'No Access', 'none', true),
        ('Frank', 'Sanders Jr.', 'Line Solutioneer', 'AVIDOR', 'Shift-A', '2022-01-10', 'No Access', 'none', true),
        ('Leon', 'Bernal', 'Line Solutioneer', 'AVIDOR', 'Shift-A', '2021-08-16', 'No Access', 'none', true),
        ('Freya', 'Aguirre', 'Line Solutioneer', 'AVIDOR', 'Shift-A', '2020-02-03', 'No Access', 'none', true),
        ('Brandon', 'Cope', 'Line Solutioneer', 'AVIDRY', 'Shift-A', '2022-07-11', 'No Access', 'none', true),
        ('Mathew', 'Veibell', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2025-09-29', 'No Access', 'none', true),
        ('Charlie', 'Corlew', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2025-09-22', 'No Access', 'none', true),
        ('Mitcell', 'Dardis', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2025-08-04', 'No Access', 'none', true),
        ('Richard', 'Vigil', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2025-06-30', 'No Access', 'none', true),
        ('Travis', 'Riggs', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2025-03-03', 'No Access', 'none', true),
        ('Kristopher', 'Young', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2024-07-08', 'No Access', 'none', true),
        ('Damon', 'Jewell', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2024-06-17', 'No Access', 'none', true),
        ('Vladimir', 'Anuchin', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2024-06-10', 'No Access', 'none', true),
        ('Jaime', 'Quijano', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2022-09-06', 'No Access', 'none', true),
        ('Oscar', 'Quiroz', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2022-03-14', 'No Access', 'none', true),
        ('Alexandria', 'Smith', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2021-09-27', 'No Access', 'none', true),
        ('Kirk', 'Antosh', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2021-04-12', 'No Access', 'none', true),
        ('Volodymyr', 'Semenov', 'Line Solutioneer', 'AVIEXT', 'Shift-A', '2020-06-08', 'No Access', 'none', true),
        ('Cooper', 'Mccain', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2025-08-04', 'No Access', 'none', true),
        ('Alexander', 'Lauda', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2025-07-21', 'No Access', 'none', true),
        ('John', 'Campbell', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2025-06-16', 'No Access', 'none', true),
        ('Bryce', 'Miller', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2025-01-27', 'No Access', 'none', true),
        ('Tim', 'Mitchell', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2024-08-26', 'No Access', 'none', true),
        ('Shawn', 'Taggart', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2023-07-10', 'No Access', 'none', true),
        ('Bastion', 'Ackerman', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2023-06-26', 'No Access', 'none', true),
        ('Hayden', 'Hansen', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2022-03-07', 'No Access', 'none', true),
        ('Ryan', 'Drumheller', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2021-08-16', 'No Access', 'none', true),
        ('Eliel', 'Herr', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2021-06-28', 'No Access', 'none', true),
        ('Whitney', 'Baumhoff', 'Line Solutioneer', 'AVIFCM', 'Shift-A', '2021-05-24', 'No Access', 'none', true),
        ('Brittany', 'Willett', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2025-11-17', 'No Access', 'none', true),
        ('Jolene', 'Williams', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2025-08-18', 'No Access', 'none', true),
        ('Griselda', 'Ayala', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2025-07-21', 'No Access', 'none', true),
        ('Ashley', 'Valverde', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2025-06-16', 'No Access', 'none', true),
        ('Dalia', 'Ponce', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2025-04-21', 'No Access', 'none', true),
        ('Lilybeth', 'Rodriguez', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2025-02-17', 'No Access', 'none', true),
        ('Michael', 'Woods', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2024-10-14', 'No Access', 'none', true),
        ('Zachary', 'Lawrence', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2024-07-15', 'No Access', 'none', true),
        ('Leticia', 'Ayala', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2024-03-25', 'No Access', 'none', true),
        ('Desiree', 'Mercado', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2023-07-17', 'No Access', 'none', true),
        ('Sophia', 'Bernal', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2023-05-01', 'No Access', 'none', true),
        ('Corriandra', 'Hansen', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2022-04-18', 'No Access', 'none', true),
        ('Evelyn', 'Apodaca', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2021-10-04', 'No Access', 'none', true),
        ('Destiny', 'Mercado', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2021-05-10', 'No Access', 'none', true),
        ('Katherine', 'Apodaca', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2020-11-02', 'No Access', 'none', true),
        ('Heather', 'Taylor', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2020-08-10', 'No Access', 'none', true),
        ('Randi', 'Atkisson', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2020-06-22', 'No Access', 'none', true),
        ('Martha', 'Barba', 'Line Solutioneer', 'AVIFIN', 'Shift-A', '2020-02-07', 'No Access', 'none', true),
        ('Oswaldo', 'Rodriguez', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2025-09-15', 'No Access', 'none', true),
        ('Eduardo', 'Guzman', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2025-05-12', 'No Access', 'none', true),
        ('Chris', 'Martin', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2025-04-28', 'No Access', 'none', true),
        ('John', 'Guilmet', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2025-04-21', 'No Access', 'none', true),
        ('David', 'Walters', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2025-01-27', 'No Access', 'none', true),
        ('Carlos', 'Rodriguez', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2024-09-03', 'No Access', 'none', true),
        ('Hipolito', 'Sarmiento', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2024-07-22', 'No Access', 'none', true),
        ('Rudy', 'Arce', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2024-02-26', 'No Access', 'none', true),
        ('Evan', 'Radcliffe', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2022-07-18', 'No Access', 'none', true),
        ('Jake', 'Butler', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-11-15', 'No Access', 'none', true),
        ('Henry', 'Morales', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-11-08', 'No Access', 'none', true),
        ('Joseph', 'Vigil', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-10-18', 'No Access', 'none', true),
        ('Garren', 'White', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-09-13', 'No Access', 'none', true),
        ('Shawn', 'Lopez', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-07-26', 'No Access', 'none', true),
        ('Angelic', 'Fairless', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-05-17', 'No Access', 'none', true),
        ('Abraham', 'Castillo', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2021-03-15', 'No Access', 'none', true),
        ('Leslee', 'Chandler', 'Line Solutioneer', 'AVIMEP', 'Shift-A', '2020-09-21', 'No Access', 'none', true),
        ('Rhea', 'Garcia', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2025-11-24', 'No Access', 'none', true),
        ('Robert', 'Hinojosa', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2025-11-17', 'No Access', 'none', true),
        ('Cliff', 'Gydesen', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2025-05-27', 'No Access', 'none', true),
        ('Michael', 'Scott', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2025-04-14', 'No Access', 'none', true),
        ('Ruben', 'Marquez', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2024-05-06', 'No Access', 'none', true),
        ('Colby', 'Bernard', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2024-03-11', 'No Access', 'none', true),
        ('Jose', 'Diaz', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2023-10-16', 'No Access', 'none', true),
        ('Salvador', 'Prieto-Garcia', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2023-07-17', 'No Access', 'none', true),
        ('Noah', 'Chavez', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2023-04-03', 'No Access', 'none', true),
        ('Robert', 'Overy', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2023-03-06', 'No Access', 'none', true),
        ('Patrick', 'Millar', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2022-12-12', 'No Access', 'none', true),
        ('Dalton', 'Bosier', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2022-11-28', 'No Access', 'none', true),
        ('Keshaun', 'Alexander', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2022-09-06', 'No Access', 'none', true),
        ('Gabrielle', 'Minor', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2022-05-31', 'No Access', 'none', true),
        ('Damon', 'Alexander', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-09-20', 'No Access', 'none', true),
        ('Robert', 'Goodall', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-08-09', 'No Access', 'none', true),
        ('David', 'Ray', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-06-28', 'No Access', 'none', true),
        ('Scott', 'Wangsgard', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-05-17', 'No Access', 'none', true),
        ('Charles', 'Colf', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-05-10', 'No Access', 'none', true),
        ('Dominic', 'Manzano', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-04-26', 'No Access', 'none', true),
        ('Adelino', 'Ramos', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-03-01', 'No Access', 'none', true),
        ('Abel', 'Castillo', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2021-01-25', 'No Access', 'none', true),
        ('Nathan', 'Schriner', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2020-09-08', 'No Access', 'none', true),
        ('Lilibeth', 'Ortega', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2020-08-24', 'No Access', 'none', true),
        ('Pam', 'Mason', 'Line Solutioneer', 'AVIOPR', 'Shift-A', '2020-03-09', 'No Access', 'none', true),
        ('Tyler', 'Stevens', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2025-03-24', 'No Access', 'none', true),
        ('Gary', 'Scaggs', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2024-10-07', 'No Access', 'none', true),
        ('Devon', 'Hollenbeck', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2024-09-19', 'No Access', 'none', true),
        ('Calvin', 'Boswell', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2024-09-16', 'No Access', 'none', true),
        ('Chuck', 'Fuqua', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2022-11-21', 'No Access', 'none', true),
        ('Chuck', 'Hoernis', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2021-07-26', 'No Access', 'none', true),
        ('Andrew', 'Mcabee', 'Line Solutioneer', 'AVISHP', 'Shift-A', '2020-08-24', 'No Access', 'none', true),
        ('Bryson', 'Jeske', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2025-05-19', 'No Access', 'none', true),
        ('Blake', 'Mcabee', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2024-05-20', 'No Access', 'none', true),
        ('Weldon', 'Stansell', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2023-01-09', 'No Access', 'none', true),
        ('Carlos', 'Delgado', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2021-01-11', 'No Access', 'none', true),
        ('Jonathan', 'Jackson', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2020-10-12', 'No Access', 'none', true),
        ('Tomas', 'Kramer', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2020-07-27', 'No Access', 'none', true),
        ('Brandon', 'Hadley', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2020-07-06', 'No Access', 'none', true),
        ('Fernando', 'Moreno', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2020-07-06', 'No Access', 'none', true),
        ('Joseph', 'Hinojosa', 'Line Solutioneer', 'AVIUTI', 'Shift-A', '2020-05-04', 'No Access', 'none', true),
        ('Adrian', 'Rocha', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2025-10-27', 'No Access', 'none', true),
        ('Clay', 'Jones', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2025-08-18', 'No Access', 'none', true),
        ('Trysten', 'Bristol', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2025-04-21', 'No Access', 'none', true),
        ('Ammon', 'Caldwell', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2025-02-17', 'No Access', 'none', true),
        ('Travis', 'Raby', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2023-12-26', 'No Access', 'none', true),
        ('Daniel', 'Martinez', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2023-07-31', 'No Access', 'none', true),
        ('Eric', 'Alley', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2022-04-11', 'No Access', 'none', true),
        ('Danny', 'Tucker', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2022-03-28', 'No Access', 'none', true),
        ('Julian', 'Castillo', 'Line Solutioneer', 'AVIWAS', 'Shift-A', '2020-06-29', 'No Access', 'none', true),
        -- Team Leaders
        ('Jacob', 'Rock', 'Team Leader', 'AVICAB', 'Shift-A', '2022-09-26', 'No Access', 'none', true),
        ('Zachary', 'Walthall', 'Team Leader', 'AVICEI', 'Shift-A', '2021-09-20', 'No Access', 'none', true),
        ('Ian', 'Kinsey', 'Team Leader', 'AVIEXT', 'Shift-A', '2021-11-22', 'No Access', 'none', true),
        ('Heriberto', 'Lopez Martin', 'Team Leader', 'AVIFCM', 'Shift-A', '2021-11-01', 'No Access', 'none', true),
        ('Cori', 'Forschler', 'Team Leader', 'AVIFIN', 'Shift-A', '2020-07-06', 'No Access', 'none', true),
        ('Juan', 'Gonzaga', 'Team Leader', 'AVIMEP', 'Shift-A', '2022-08-29', 'No Access', 'none', true),
        ('Bryan', 'Rodgers', 'Team Leader', 'AVIMEP', 'Shift-A', '2020-10-12', 'No Access', 'none', true),
        ('Phillip', 'Crust', 'Team Leader', 'AVIOPR', 'Shift-A', '2021-08-23', 'No Access', 'none', true),
        ('Toby', 'Carlock', 'Team Leader', 'AVIREC', 'Shift-A', '2020-03-16', 'No Access', 'none', true),
        ('Aaron', 'High', 'Team Leader', 'AVISHP', 'Shift-A', '2021-07-06', 'No Access', 'none', true),
        ('Travis', 'Brennan', 'Team Leader', 'AVIWAS', 'Shift-A', '2024-03-11', 'No Access', 'none', true)
    ON CONFLICT DO NOTHING;

    -- Verify import count
    SELECT 
        'Total Employees' as metric,
        COUNT(*) as count 
    FROM employees
    UNION ALL
    SELECT 
        'By Department: ' || department,
        COUNT(*)
    FROM employees
    GROUP BY department
    ORDER BY metric;
